# Generated by Django 3.1.6 on 2021-03-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100, verbose_name='게임명')),
                ('game_id', models.CharField(max_length=100, verbose_name='게임내 유저명')),
                ('tier', models.CharField(max_length=100, verbose_name='티어')),
            ],
        ),
    ]
